version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
    commands:
      - echo "INSTALL PHASE"
  build:
    commands:
      - echo "DEPLOY PHASE"
artifacts:
  files:
    - '**/*'
