version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
    commands:
      - npm i -g aws-cdk
      - pip install -r requirements.txt
  pre_build:
    commands:
      - cdk diff
  build:
    commands:
      - cdk deploy --require-approval never